"""Strongly-typed contracts and schemas for the modular anti-spoofing pipeline."""

from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, ConfigDict


class AudioFormat(str, Enum):
    WAV = "WAV"
    MP3 = "MP3"
    FLAC = "FLAC"
    OGG = "OGG"
    RAW_PCM = "RAW_PCM"
    UNKNOWN = "UNKNOWN"


class ValidationStatus(str, Enum):
    VALID = "VALID"
    INVALID = "INVALID"
    CORRUPTED = "CORRUPTED"
    EMPTY = "EMPTY"


class AudioValidationResult(BaseModel):
    """Validation report generated by AudioValidator."""
    model_config = ConfigDict(extra="forbid")

    status: ValidationStatus
    is_valid: bool
    detected_format: AudioFormat
    sample_rate: int
    channels: int
    duration_seconds: float
    samples_count: int
    clipping_ratio: float = 0.0
    is_silent: bool = False
    validation_notes: List[str] = Field(default_factory=list)


class AudioSegment(BaseModel):
    """A segmented chunk of audio for model inference."""
    model_config = ConfigDict(extra="forbid", arbitrary_types_allowed=True)

    segment_index: int
    start_time_s: float
    end_time_s: float
    duration_s: float
    samples_count: int
    is_voiced: bool = True
    rms_energy: float = 0.0


class PreprocessingSummary(BaseModel):
    """Metadata regarding preprocessing, resampling, and VAD."""
    model_config = ConfigDict(extra="forbid")

    original_sample_rate: int
    target_sample_rate: int = 16000
    original_channels: int
    original_duration_s: float
    active_speech_duration_s: float
    voiced_ratio: float
    snr_db: float
    num_segments: int
    peak_amplitude: float
    normalization_gain_db: float


class AcousticFeaturesSummary(BaseModel):
    """Acoustic feature metrics extracted from the audio signal."""
    model_config = ConfigDict(extra="forbid")

    spectral_centroid_mean_hz: float
    spectral_bandwidth_mean_hz: float
    spectral_flatness_mean: float
    spectral_rolloff_mean_hz: float
    f0_mean_hz: Optional[float] = None
    f0_std_hz: Optional[float] = None
    f0_voiced_fraction: float = 0.0
    jitter_local: Optional[float] = None
    shimmer_local: Optional[float] = None
    rms_energy_mean: float = 0.0
    zero_crossing_rate_mean: float = 0.0


class SegmentInferenceScore(BaseModel):
    """Detector score on an individual audio segment."""
    model_config = ConfigDict(extra="forbid")

    segment_index: int
    start_time_s: float
    end_time_s: float
    p_fake: float
    p_real: float
    confidence: float
    is_spoof_suspected: bool


class DetectorResult(BaseModel):
    """Inference output from an individual anti-spoofing detector."""
    model_config = ConfigDict(extra="forbid")

    detector_id: str
    model_version: str
    detector_type: str  # e.g. "NEURAL_WAV2VEC2", "ACOUSTIC_FORENSIC"
    p_fake: float
    p_real: float
    raw_confidence: float
    segment_scores: List[SegmentInferenceScore] = Field(default_factory=list)
    latency_ms: float
    status: str = "OK"  # "OK", "DEGRADED", "ERROR"
    error_message: Optional[str] = None


class ForensicAnomaly(BaseModel):
    """Specific forensic acoustic anomaly detected in the voice signal."""
    model_config = ConfigDict(extra="forbid")

    anomaly_code: str
    severity: str  # "LOW", "MEDIUM", "HIGH", "CRITICAL"
    description: str
    observed_value: float
    reference_threshold: float


class ForensicEvidence(BaseModel):
    """Aggregated evidence generated across all detectors and DSP modules."""
    model_config = ConfigDict(extra="forbid")

    detectors_evaluated: List[str]
    active_detectors_count: int
    anomalies_detected: List[ForensicAnomaly] = Field(default_factory=list)
    segment_variance: float = 0.0
    temporal_consistency_score: float = 1.0
    quality_conditioned_weight: float = 1.0


class FusedScore(BaseModel):
    """Fused score prior to final calibration."""
    model_config = ConfigDict(extra="forbid")

    fused_p_synthetic: float
    raw_confidence: float
    detector_weights: Dict[str, float]
    fusion_method: str = "BAYESIAN_QUALITY_WEIGHTED"


class CalibratedScore(BaseModel):
    """Calibrated probability of synthetic origin and confidence interval."""
    model_config = ConfigDict(extra="forbid")

    calibrated_p_synthetic: float
    calibrated_confidence: float
    confidence_interval_low: float
    confidence_interval_high: float
    uncertainty_level: str  # "LOW", "MODERATE", "HIGH"
    shrinkage_factor_applied: float = 1.0


class PolicyVerdict(str, Enum):
    ALLOW = "ALLOW"
    STEP_UP = "STEP_UP"
    HOLD = "HOLD"
    ESCALATE = "ESCALATE"


class RiskBand(str, Enum):
    LOW = "LOW"
    ELEVATED = "ELEVATED"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    UNCERTAIN = "UNCERTAIN"


class RiskDecisionResult(BaseModel):
    """Final risk assessment and policy action."""
    model_config = ConfigDict(extra="forbid")

    risk_band: RiskBand
    risk_score: float  # 0.0 to 1.0
    policy_action: PolicyVerdict
    matched_policy_rule: str
    requires_step_up_verification: bool
    requires_transaction_hold: bool


class RiskFactorAttribution(BaseModel):
    """Attribution factor explaining the risk score."""
    model_config = ConfigDict(extra="forbid")

    factor_name: str
    category: str  # "ACOUSTIC_NEURAL", "DSP_FORENSIC", "SIGNAL_QUALITY", "TRANSACTION_CONTEXT"
    contribution: float  # -1.0 (towards genuine) to +1.0 (towards synthetic)
    weight: float
    description: str


class StructuredExplanation(BaseModel):
    """Machine-readable and human-interpretable decision explanation."""
    model_config = ConfigDict(extra="forbid")

    summary_statement: str
    primary_risk_drivers: List[RiskFactorAttribution] = Field(default_factory=list)
    forensic_anomaly_triggers: List[str] = Field(default_factory=list)
    signal_quality_caveats: List[str] = Field(default_factory=list)


class TransactionContext(BaseModel):
    """Contextual transaction parameters if evaluating a financial session."""
    model_config = ConfigDict(extra="ignore")

    caller_identity: Optional[str] = None
    caller_phone: Optional[str] = None
    transaction_id: Optional[str] = None
    amount: Optional[Decimal] = None
    currency: Optional[str] = "INR"
    beneficiary: Optional[str] = None
    beneficiary_novelty: Optional[str] = "KNOWN"  # "KNOWN", "NEW"
    transaction_type: Optional[str] = "WIRE_TRANSFER"
    urgency_claimed: bool = False
    callback_refused: bool = False


class OverallRisk(BaseModel):
    """Aggregated risk assessment and tier classification."""
    model_config = ConfigDict(extra="forbid")

    risk_score: float  # 0.0 (benign) to 1.0 (severe threat)
    risk_band: RiskBand  # "VERY_LOW", "LOW", "ELEVATED", "HIGH", "CRITICAL", "UNCERTAIN"
    severity_level: str  # "LOW", "MEDIUM", "HIGH", "CRITICAL", "UNCERTAIN"
    summary: str


class DecisionVerdict(BaseModel):
    """Policy action verdict and governance rule match."""
    model_config = ConfigDict(extra="forbid")

    verdict: PolicyVerdict  # "ALLOW", "STEP_UP", "HOLD", "ESCALATE"
    matched_rule: str
    requires_step_up: bool
    requires_hold: bool
    action_narrative: str


class ConfidenceScore(BaseModel):
    """Calibrated statistical confidence with bounded error intervals."""
    model_config = ConfigDict(extra="forbid")

    score: float  # 0.0 to 1.0
    uncertainty_level: str  # "VERY_LOW", "LOW", "MODERATE", "HIGH"
    confidence_interval: List[float]  # [ci_low, ci_high]
    shrinkage_applied: float


class DetectorScoreItem(BaseModel):
    """Computed score emitted by a distinct detector/expert."""
    model_config = ConfigDict(extra="forbid")

    detector_id: str
    detector_name: str
    detector_type: str
    model_version: str
    p_synthetic: float
    confidence: float
    status: str  # "OK", "DEFERRED", "ERROR"
    latency_ms: float
    weight_in_fusion: float


class EvidenceItem(BaseModel):
    """Individual forensic evidence piece computed during signal processing."""
    model_config = ConfigDict(extra="forbid")

    signal: str
    category: str  # "NEURAL_ACOUSTIC", "PHYSICAL_DSP", "SPEAKER_BIOMETRICS", "SIGNAL_QUALITY", "TRANSACTION_CONTEXT"
    score: float
    severity: str  # "INFO", "LOW", "MEDIUM", "HIGH", "CRITICAL"
    explanation: str


class ProcessingLatency(BaseModel):
    """Execution latency breakdown in milliseconds."""
    model_config = ConfigDict(extra="forbid")

    total_ms: float
    validation_ms: float
    preprocessing_ms: float
    feature_extraction_ms: float
    detector_breakdown_ms: Dict[str, float]
    fusion_and_calibration_ms: float


class AudioMetadata(BaseModel):
    """Extracted physical and acoustic metadata of the processed audio."""
    model_config = ConfigDict(extra="forbid")

    duration_s: float
    active_speech_duration_s: float
    sample_rate_hz: int
    channels: int
    snr_db: float
    voiced_ratio: float
    clipping_detected: bool
    peak_amplitude_dbfs: float


class InferenceRequest(BaseModel):
    """Inference request payload."""
    model_config = ConfigDict(extra="ignore")

    audio_base64: Optional[str] = None
    audio_fixture: Optional[str] = None
    session_id: Optional[str] = None
    transaction: Optional[TransactionContext] = None
    context_parameters: Optional[Dict[str, Any]] = None


class InferenceResponse(BaseModel):
    """Canonical, machine-readable structured response emitted by the pipeline."""
    model_config = ConfigDict(extra="forbid")

    request_id: str
    session_id: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    is_valid_audio: bool
    pipeline_version: str = "voiceshield-pipeline-v3.0"
    processing_time: float

    # First-class structured forensic result
    overall_risk: OverallRisk
    decision: DecisionVerdict
    confidence: ConfidenceScore
    detector_scores: List[DetectorScoreItem]
    evidence_items: List[EvidenceItem]
    processing_latency: ProcessingLatency
    model_versions: Dict[str, str]
    audio_metadata: AudioMetadata

    # Convenience shortcuts matching forensic result specification
    risk_score: Optional[float] = None
    confidence_score: Optional[float] = None
    processing_time_ms: Optional[float] = None
    models: Optional[Dict[str, str]] = None

    # Backward-compatible telemetry fields
    verdict: PolicyVerdict
    risk_band: RiskBand
    calibrated_p_synthetic: float
    validation: AudioValidationResult
    preprocessing: PreprocessingSummary
    features: AcousticFeaturesSummary
    detectors: List[DetectorResult]
    evidence: ForensicEvidence
    calibration: CalibratedScore
    explanation: StructuredExplanation
    execution_time_ms: float


DetectRequest = InferenceRequest
DetectResponse = InferenceResponse

