"""
app.py — SIH26104 Voice Authenticity Engine (DEMO PROTOTYPE)
==============================================================
This is a hackathon demo, not the production system described in the pitch
deck. It exists to make the Tier-1 pipeline (ingest -> analyze -> score ->
threshold -> action) tangible and clickable on stage. See README.md for
exactly which parts are "real" vs simplified stand-ins.
"""

import time
import numpy as np
import librosa
import soundfile as sf
import streamlit as st
import plotly.graph_objects as go

from features import extract_features, FEATURE_NAMES
from risk_engine import run_pipeline

st.set_page_config(page_title="Voice Authenticity Engine — Demo", page_icon="🎙️", layout="wide")

# ---------------------------------------------------------------- styling ---
st.markdown("""
<style>
.big-score {font-size: 3rem; font-weight: 700; margin-bottom: 0;}
.action-allow {color: #1a9e46;}
.action-flag {color: #d68a00;}
.action-block {color: #d32f2f;}
.small-note {color: #888; font-size: 0.85rem;}
</style>
""", unsafe_allow_html=True)

st.title("🎙️ Real-Time Voice Authenticity Engine")
st.caption("SIH26104 — Voice Cloning Detection · Demo Prototype (not the production model)")

# ---------------------------------------------------------------- sidebar ---
with st.sidebar:
    st.header("Call context")
    st.write("Simulates the metadata a telecom/bank integration would already have.")
    unknown_number = st.toggle("Unknown / unverified number", value=True)
    transaction_request = st.toggle("Call requests a financial transaction", value=True)
    high_urgency = st.toggle("High-pressure / urgency language detected", value=False)

    st.divider()
    st.header("Action thresholds")
    st.write("These would be set per-deployment by the bank/telecom in production.")
    allow_max = st.slider("Allow below", 0, 100, 30)
    flag_max = st.slider("Flag for callback below (else Block)", allow_max, 100, 65)

    st.divider()
    st.caption(
        "Demo note: acoustic scoring here uses classical DSP markers "
        "(jitter, shimmer, spectral flatness, etc.) as an explainable, "
        "GPU-free stand-in for the WavLM classifier described in the deck. "
        "See README.md."
    )

# ---------------------------------------------------------------- input -----
st.subheader("1. Provide a call audio sample")
tab1, tab2, tab3 = st.tabs(["🎤 Record live", "📁 Upload a file", "🤖 Use bundled synthetic sample"])

audio_bytes = None
audio_source_label = None

with tab1:
    st.write("Record a few seconds of your own voice — this is your **genuine** control sample.")
    rec = st.audio_input("Record")
    if rec is not None:
        audio_bytes = rec.read()
        audio_source_label = "Live microphone recording"

with tab2:
    up = st.file_uploader("Upload a WAV/MP3 clip", type=["wav", "mp3", "m4a", "flac"])
    if up is not None:
        audio_bytes = up.read()
        audio_source_label = f"Uploaded file: {up.name}"

with tab3:
    st.write(
        "Plays a clip generated by an offline TTS engine (espeak-ng) — a stand-in "
        "for a cloned/synthetic voice, since we can't play a real deepfake sample "
        "safely in a public demo."
    )
    try:
        with open("sample_audio/synthetic_sample.wav", "rb") as f:
            synth_bytes = f.read()
        st.audio(synth_bytes, format="audio/wav")
        if st.button("Analyze this synthetic sample"):
            audio_bytes = synth_bytes
            audio_source_label = "Bundled synthetic (TTS) sample"
    except FileNotFoundError:
        st.warning("Run `python synth_bootstrap.py` once to generate the bundled sample.")

# ---------------------------------------------------------------- pipeline --
if audio_bytes:
    st.subheader("2. Real-time analysis pipeline")
    progress = st.progress(0, text="Ingesting audio stream...")
    time.sleep(0.25)

    import io
    y, sr = sf.read(io.BytesIO(audio_bytes))
    if y.ndim > 1:
        y = np.mean(y, axis=1)
    y = y.astype(np.float32)
    progress.progress(30, text="Running acoustic authenticity model...")
    time.sleep(0.2)

    raw_features = extract_features(y, sr)
    progress.progress(65, text="Combining with call-risk metadata...")
    time.sleep(0.2)

    result = run_pipeline(
        raw_features, unknown_number, transaction_request, high_urgency,
        allow_max=allow_max, flag_max=flag_max,
    )
    progress.progress(100, text="Done.")
    time.sleep(0.15)
    progress.empty()

    st.caption(f"Source: {audio_source_label}")

    col1, col2, col3 = st.columns([1, 1, 1.2])

    with col1:
        st.markdown("**Acoustic authenticity risk**")
        st.markdown(f"<p class='big-score'>{result.acoustic_risk:.0f}<span style='font-size:1.2rem'>/100</span></p>", unsafe_allow_html=True)
        st.caption("Higher = more signs of synthetic/cloned speech")

    with col2:
        st.markdown("**Composite risk score**")
        st.markdown(f"<p class='big-score'>{result.composite_risk:.0f}<span style='font-size:1.2rem'>/100</span></p>", unsafe_allow_html=True)
        st.caption("Acoustic score (75%) + call metadata (25%)")

    with col3:
        action_map = {
            "ALLOW": ("✅ ALLOW", "action-allow"),
            "FLAG_FOR_CALLBACK": ("⚠️ FLAG FOR CALLBACK VERIFICATION", "action-flag"),
            "BLOCK": ("⛔ BLOCK", "action-block"),
        }
        label, css = action_map[result.action]
        st.markdown("**Recommended action**")
        st.markdown(f"<p class='big-score {css}' style='font-size:1.8rem'>{label}</p>", unsafe_allow_html=True)

    st.divider()

    # ------------------------------------------------------- explainability
    st.subheader("3. Why this score? (explainability)")
    ecol1, ecol2 = st.columns([1.3, 1])

    with ecol1:
        labels = [c["label"] for c in result.feature_contributions]
        risks = [c["risk_contribution"] for c in result.feature_contributions]
        fig = go.Figure(go.Bar(
            x=risks, y=labels, orientation="h",
            marker_color=["#d32f2f" if r > 60 else "#d68a00" if r > 30 else "#1a9e46" for r in risks],
        ))
        fig.update_layout(
            title="Acoustic feature risk contribution",
            xaxis_title="Risk contribution (0-100)",
            height=320, margin=dict(l=10, r=10, t=40, b=10),
        )
        st.plotly_chart(fig, use_container_width=True)

    with ecol2:
        st.markdown("**Call-metadata contribution**")
        for c in result.metadata_contributions:
            icon = "🔴" if c["active"] else "⚪"
            st.write(f"{icon} {c['label']} — **+{c['points']} pts**" if c["active"] else f"{icon} {c['label']}")

    with st.expander("Raw feature values (for the judges who ask)"):
        st.json(raw_features)

    st.divider()
    st.subheader("4. Waveform & spectrogram")
    wcol1, wcol2 = st.columns(2)
    with wcol1:
        wfig = go.Figure(go.Scatter(y=y[::max(1, len(y)//2000)], mode="lines", line=dict(width=1)))
        wfig.update_layout(title="Waveform", height=250, margin=dict(l=10, r=10, t=40, b=10))
        st.plotly_chart(wfig, use_container_width=True)
    with wcol2:
        S = librosa.amplitude_to_db(np.abs(librosa.stft(y)), ref=np.max)
        sfig = go.Figure(go.Heatmap(z=S, colorscale="Viridis"))
        sfig.update_layout(title="Spectrogram", height=250, margin=dict(l=10, r=10, t=40, b=10))
        st.plotly_chart(sfig, use_container_width=True)

else:
    st.info("Record, upload, or select the bundled sample above to run the pipeline.")

st.divider()
with st.expander("⚠️ Known limitations of this demo (read before presenting)"):
    st.markdown("""
    - Uses classical DSP features, **not** a WavLM classifier fine-tuned on ASVspoof/WaveFake —
      that requires GPU training time and licensed datasets outside a hackathon demo window.
    - Thresholds/weights are hand-set from published anti-spoofing literature, not fitted on a
      held-out labeled set — accuracy has **not** been benchmarked (no EER/FPR numbers from this
      demo should be quoted as the project's real numbers; those come from the model described
      in the deck).
    - No true streaming/chunked inference — this analyzes a complete clip. The "ingest → analyze"
      progress bar illustrates the intended real-time flow.
    - Very short clips (<1s) and heavily denoised/post-processed audio will not be reliably scored.
    """)
