"""
risk_engine.py
--------------
Two-layer scoring, mirroring the Tier-1 architecture in the pitch deck:

  Layer 1 (acoustic):  raw DSP features -> normalized "unnaturalness" scores -> 
                        weighted composite acoustic risk (0-100)
  Layer 2 (contextual): acoustic risk + call metadata (known/unknown number,
                        transaction type, urgency) -> composite risk score (0-100)
  Decision layer:       composite score -> Allow / Flag for callback / Block,
                        against configurable thresholds

Every number that goes into the final score is retained, so the UI can show
*why* a call was flagged (explainability), not just the flag itself.
"""

from __future__ import annotations
from dataclasses import dataclass, field

# Empirically-reasonable reference points for "what genuine human speech looks
# like" on each feature. These are intentionally documented and tunable —
# swap in values fitted from real ASVspoof/WaveFake statistics for production.

# NOTE ON CALIBRATION: these genuine_min/genuine_max reference points and weights
# are hand-set from general anti-spoofing literature intuition, NOT fitted on a
# labeled dataset. They are demo-tuned against the bundled sample generated by
# synth_bootstrap.py, which on Windows falls back to the SAPI5 TTS voice
# (espeak-ng is Linux/macOS-only) — SAPI5's output is measurably more
# prosodically expressive than espeak-ng's, so jitter/shimmer/spectral-flux/
# mfcc-delta only weakly separate it from genuine speech on this platform.
# spectral_flatness remains the strongest, most reliable discriminator for
# this specific stand-in, so it carries the dominant weight; pause_uniformity
# is next. If you swap in a different TTS/cloning engine for your demo sample
# (e.g. real espeak-ng on Linux/macOS), re-run the calibration check in
# README.md and re-tune these weights before presenting.
REFERENCE = {
    "pitch_jitter":        {"genuine_min": 0.015, "weight": 0.08, "direction": "low_is_risky"},
    "amp_shimmer":         {"genuine_min": 0.18,  "weight": 0.06, "direction": "low_is_risky"},
    "spectral_flatness":   {"genuine_max": 0.15,  "weight": 0.38, "direction": "high_is_risky"},
    "spectral_flux":       {"genuine_min": 25.0,  "weight": 0.08, "direction": "low_is_risky"},
    "mfcc_delta_var":      {"genuine_min": 30.0,  "weight": 0.08, "direction": "low_is_risky"},
    "harmonic_ratio":      {"genuine_max": 0.55,  "weight": 0.18, "direction": "high_is_risky"},
    "pause_uniformity":    {"genuine_max": 0.55,  "weight": 0.14, "direction": "high_is_risky"},
}

FEATURE_LABELS = {
    "pitch_jitter": "Pitch micro-variation (jitter)",
    "amp_shimmer": "Loudness micro-variation (shimmer)",
    "spectral_flatness": "Spectral flatness",
    "spectral_flux": "Frame-to-frame spectral change",
    "mfcc_delta_var": "Micro-prosody variance",
    "harmonic_ratio": "Harmonic-to-noise ratio",
    "pause_uniformity": "Pause-length uniformity",
}

METADATA_WEIGHTS = {
    "unknown_number": 18,
    "transaction_request": 22,
    "high_urgency": 15,
}


@dataclass
class RiskResult:
    acoustic_risk: float
    composite_risk: float
    action: str
    feature_contributions: list = field(default_factory=list)
    metadata_contributions: list = field(default_factory=list)


def _feature_risk(name: str, value: float) -> float:
    """Map a raw feature value to a 0-100 'risk' contribution for that feature.

    Uses a sqrt curve rather than a straight line so that moderate deviations
    from the "genuine" reference point (which is what real DSP measurements
    tend to produce, rather than the extreme values a linear scale needs to
    look dramatic) still register as a visible risk contribution in the demo.
    """
    ref = REFERENCE[name]
    if ref["direction"] == "low_is_risky":
        floor = ref["genuine_min"]
        ratio = value / (floor + 1e-6)
        deviation = max(0.0, min(1.0, 1.0 - ratio))
    else:
        ceiling = ref["genuine_max"]
        ratio = value / (ceiling + 1e-6)
        deviation = max(0.0, min(1.0, ratio - 1.0 + 0.5))
    risk = (deviation ** 0.55) * 100
    return risk


def score_acoustics(raw_features: dict) -> tuple[float, list]:
    contributions = []
    weighted_sum = 0.0
    for name, value in raw_features.items():
        ref = REFERENCE[name]
        risk = _feature_risk(name, value)
        weighted = risk * ref["weight"]
        weighted_sum += weighted
        contributions.append({
            "feature": name,
            "label": FEATURE_LABELS[name],
            "raw_value": value,
            "risk_contribution": risk,
            "weight": ref["weight"],
        })
    contributions.sort(key=lambda c: c["risk_contribution"] * c["weight"], reverse=True)
    acoustic_risk = max(0.0, min(100.0, weighted_sum))
    return acoustic_risk, contributions


def score_metadata(unknown_number: bool, transaction_request: bool, high_urgency: bool) -> tuple[float, list]:
    contributions = []
    total = 0.0
    flags = {
        "unknown_number": unknown_number,
        "transaction_request": transaction_request,
        "high_urgency": high_urgency,
    }
    labels = {
        "unknown_number": "Call from unknown / unverified number",
        "transaction_request": "Call requests a financial transaction",
        "high_urgency": "Caller is using high-pressure / urgency language",
    }
    for key, active in flags.items():
        pts = METADATA_WEIGHTS[key] if active else 0
        total += pts
        contributions.append({"feature": key, "label": labels[key], "active": active, "points": pts})
    return total, contributions


def decide_action(composite_risk: float, allow_max: float = 30, flag_max: float = 65) -> str:
    if composite_risk <= allow_max:
        return "ALLOW"
    if composite_risk <= flag_max:
        return "FLAG_FOR_CALLBACK"
    return "BLOCK"


def run_pipeline(
    raw_features: dict,
    unknown_number: bool,
    transaction_request: bool,
    high_urgency: bool,
    allow_max: float = 30,
    flag_max: float = 65,
) -> RiskResult:
    acoustic_risk, feat_contribs = score_acoustics(raw_features)
    meta_risk, meta_contribs = score_metadata(unknown_number, transaction_request, high_urgency)

    # Acoustic signal dominates (it's the actual fraud-detection evidence);
    # metadata nudges the score the way a real risk-triage system would.
    composite = max(0.0, min(100.0, acoustic_risk * 0.75 + meta_risk * 0.25))
    action = decide_action(composite, allow_max, flag_max)

    return RiskResult(
        acoustic_risk=acoustic_risk,
        composite_risk=composite,
        action=action,
        feature_contributions=feat_contribs,
        metadata_contributions=meta_contribs,
    )
